#ifndef _ASM_BIOS_DEF_H
#define _ASM_BIOS_DEF_H

#define BIOS_SETTIMER 0
#define BIOS_PUTCHAR 1
#define BIOS_GETCHAR 2
#define BIOS_SEND_IPI 4
#define BIOS_PUTSTR 9
#define BIOS_SDWRITE 10
#define BIOS_SDREAD 11
#define BIOS_FDTREAD 12
#define BIOS_LOGGING 14

#endif // _ASM_BIOS_DEF_H
