add-symbol-file /home/stu/jinyang20/Project3_Interactive_OS_and_Process_Management/build/add2
add-symbol-file /home/stu/jinyang20/Project3_Interactive_OS_and_Process_Management/build/add
add-symbol-file /home/stu/jinyang20/Project3_Interactive_OS_and_Process_Management/build/bootblock
add-symbol-file /home/stu/jinyang20/Project3_Interactive_OS_and_Process_Management/build/fly
add-symbol-file /home/stu/jinyang20/Project3_Interactive_OS_and_Process_Management/build/lock1
add-symbol-file /home/stu/jinyang20/Project3_Interactive_OS_and_Process_Management/build/lock2
add-symbol-file /home/stu/jinyang20/Project3_Interactive_OS_and_Process_Management/build/lock3
add-symbol-file /home/stu/jinyang20/Project3_Interactive_OS_and_Process_Management/build/main
add-symbol-file /home/stu/jinyang20/Project3_Interactive_OS_and_Process_Management/build/print1
add-symbol-file /home/stu/jinyang20/Project3_Interactive_OS_and_Process_Management/build/print2
add-symbol-file /home/stu/jinyang20/Project3_Interactive_OS_and_Process_Management/build/shell
add-symbol-file /home/stu/jinyang20/Project3_Interactive_OS_and_Process_Management/build/sleep
add-symbol-file /home/stu/jinyang20/Project3_Interactive_OS_and_Process_Management/build/timer
